// app/api/research/alert/test/route.ts
//
// Phase 11 — operator-facing test alert. Sends a synthetic
// SUFFICIENT report through the Pushover client to verify config.
// No criteria check (forceTest=true); skips silently when keys
// aren't configured.

import { sendAlert, isPushoverConfigured } from "@/lib/research/alerts";
import type { ResearchReport } from "@/lib/research/types";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

export async function POST() {
  const configured = await isPushoverConfigured();
  if (!configured) {
    return Response.json(
      {
        ok: false,
        sent: false,
        reason:
          "Pushover credentials not configured — set operatorPushoverUserKey + operatorPushoverApiToken in Settings",
      },
      { status: 200 }
    );
  }

  const now = new Date().toISOString();
  const fakeReport: ResearchReport = {
    id: `test-${Date.now().toString(36)}`,
    intent: "ai_updates",
    queries: [],
    results: [],
    crawledPages: [],
    summary:
      "ARGOS Phase 11 test alert — Pushover delivery verified. If you see this on your device, the integration is working.",
    findings: [
      "Test message generated by /api/research/alert/test.",
      "This is not a real research result.",
    ],
    citations: [
      "[1] ARGOS Test Alert — argos — https://localhost/",
    ],
    confidenceScore: 1.0,
    conflicts: [],
    generatedAt: now,
    ttlMinutes: 60,
    iteration: 1,
    quality: "SUFFICIENT",
  };

  const result = await sendAlert(fakeReport, {
    forceTest: true,
    reasonOverride: "test alert (operator-triggered)",
  });
  return Response.json({ ok: result.sent, ...result });
}
