// chat-export.ts
//
// Pure functions for serializing in-memory chat sessions to markdown.
// Used by ChatPane's "Export" button to let the operator save a session
// to a .md file without any host-side persistence (Rule #1 compliant —
// the download lives wherever the browser saves files, the app does
// not write to host disk).

import type { ChatMessage, CitedHit } from "./store";
import type { PersonaId } from "./personas";
import { PERSONA_BY_ID } from "./personas";

export interface ExportContext {
  /** Currently active model, copied into the header. */
  model: string;
  /** When the export was triggered. Defaults to Date.now() if omitted. */
  exportedAt?: number;
  /** Override the displayed persona name; otherwise inferred from the
   *  most recent assistant message's personaId. */
  personaName?: string;
}

/**
 * Render a chat session as markdown. Sections:
 *   - Header (model, persona, exported-at timestamp)
 *   - One block per non-system message
 *   - Assistant blocks include citation footnotes when present
 *
 * System messages are skipped — they're framing for the model, not
 * conversational artifacts the operator wants to share.
 */
export function chatToMarkdown(
  messages: ChatMessage[],
  ctx: ExportContext
): string {
  const exportedAt = ctx.exportedAt ?? Date.now();
  const isoTs = new Date(exportedAt).toISOString();

  const personaName =
    ctx.personaName ?? inferPersonaName(messages) ?? "ARGOS";

  const lines: string[] = [];
  lines.push(`# ARGOS Chat — ${personaName}`);
  lines.push("");
  lines.push(`**Exported:** ${isoTs}  `);
  lines.push(`**Model:** ${ctx.model}  `);
  lines.push(`**Messages:** ${messages.filter((m) => m.role !== "system").length}`);
  lines.push("");
  lines.push("---");
  lines.push("");

  for (const msg of messages) {
    if (msg.role === "system") continue;
    const speaker =
      msg.role === "user"
        ? "User"
        : msg.personaId
          ? PERSONA_BY_ID[msg.personaId]?.name ?? msg.role
          : "Assistant";
    lines.push(`### ${speaker}`);
    lines.push("");
    // Preserve content as-is; markdown handles linebreaks via blank lines.
    lines.push(msg.content.trim() || "*(empty)*");
    lines.push("");
    if (msg.retrievalHits && msg.retrievalHits.length > 0) {
      lines.push("**Citations:**");
      lines.push("");
      for (const hit of msg.retrievalHits) {
        lines.push(formatCitation(hit));
      }
      lines.push("");
    }
    if (msg.retrievalError) {
      lines.push(`> _Retrieval error: ${msg.retrievalError}_`);
      lines.push("");
    }
    if (msg.errored) {
      lines.push(`> _This message errored mid-stream._`);
      lines.push("");
    }
  }

  lines.push("---");
  lines.push("");
  lines.push("_Generated by ARGOS — local-first AI workstation._");

  return lines.join("\n");
}

/**
 * Filename for a chat export: ISO-date + persona slug + short hash.
 * Avoids collisions when multiple exports happen in the same minute.
 */
export function exportFilename(personaName: string, exportedAt: number): string {
  const d = new Date(exportedAt);
  const yyyy = d.getUTCFullYear();
  const mm = String(d.getUTCMonth() + 1).padStart(2, "0");
  const dd = String(d.getUTCDate()).padStart(2, "0");
  const hh = String(d.getUTCHours()).padStart(2, "0");
  const mi = String(d.getUTCMinutes()).padStart(2, "0");
  const slug = personaName
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
  return `argos-chat-${yyyy}${mm}${dd}-${hh}${mi}-${slug}.md`;
}

function inferPersonaName(messages: ChatMessage[]): string | undefined {
  for (let i = messages.length - 1; i >= 0; i--) {
    const m = messages[i];
    if (m.role === "assistant" && m.personaId) {
      const p = PERSONA_BY_ID[m.personaId as PersonaId];
      if (p) return p.name;
    }
  }
  return undefined;
}

function formatCitation(hit: CitedHit): string {
  const score = hit.score.toFixed(3);
  // Trim quoted source text to keep the markdown readable
  const preview = hit.text.replace(/\s+/g, " ").trim().slice(0, 240);
  const ellipsis = hit.text.length > 240 ? "…" : "";
  return `- **[${hit.index}]** \`${hit.filename}\` chunk ${hit.chunkIndex} (score ${score}) — ${preview}${ellipsis}`;
}
